# spring
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/blog
     username: root
     password: 123456
     driver-class-name: com.mysql.cj.jdbc.Driver

#     liquibase (drop-first default value = false)
  liquibase:
      enabled: true
      change-log: classpath:/liquibase/db-changelog-master.xml
      drop-first: false

#server:
#    port: 8080
#    servlet:
#        context-path: /